### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by paradite** [kite1988/IMSForWordNews#2]
Hi Chen Tao, this is code is being hosted on heroku and live? If so, who is maintaining it?

Also, is there any reasons why machine translation is used as default instead of this? I want to use this for the next iteration of WordNews if it provides better translation results.

**Comment by kite1988** [comment]
I have transferred the ownership of all the heroku apps to IDMI team, but I guess the code is still live.  You may contact them for details.

We do not have a particular reason of setting machine translation as a default. We leave the selection of translation engines to the user (i.e., a setting in the front end).

**Comment by paradite** [comment]
Thanks. I will contact them then.
